import type { BoardSquare } from '@/types/game'

export const BOARD_SQUARES: BoardSquare[] = [
  {
    id: 0,
    label: 'START',
    shortLabel: 'START',
    effectLabel: '',
    icon: '🚩',
    x: 14,
    y: 16,
    accent: true,
    coupon: {
      id: 'start',
      title: 'スタート',
      description: 'ゲーム開始',
      type: 'none',
    },
  },
  {
    id: 1,
    label: '100円OFF',
    shortLabel: '100円OFF',
    effectLabel: 'クーポン',
    icon: '🎫',
    x: 34,
    y: 14,
    coupon: {
      id: '100off',
      title: '100円OFF',
      description: 'お会計から100円引き',
      type: 'discount',
    },
  },
  {
    id: 2,
    label: 'ハズレ',
    shortLabel: 'ハズレ',
    effectLabel: 'ざんねん',
    icon: '💭',
    x: 54,
    y: 18,
    coupon: {
      id: 'lose1',
      title: '今回はハズレ',
      description: '次のチャンスを狙おう',
      type: 'none',
    },
  },
  {
    id: 3,
    label: 'ドリンク無料',
    shortLabel: 'ドリンク無料',
    effectLabel: '1杯無料',
    icon: '🥤',
    x: 74,
    y: 14,
    coupon: {
      id: 'drink1',
      title: 'ドリンク1杯無料',
      description: '対象ドリンクから1杯無料',
      type: 'free',
    },
  },
  {
    id: 4,
    label: '200円OFF',
    shortLabel: '200円OFF',
    effectLabel: 'クーポン',
    icon: '🎫',
    x: 86,
    y: 25,
    coupon: {
      id: '200off',
      title: '200円OFF',
      description: 'お会計から200円引き',
      type: 'discount',
    },
  },
  {
    id: 5,
    label: 'もう1回',
    shortLabel: 'もう1回',
    effectLabel: 'チャンス',
    icon: '🎲',
    x: 72,
    y: 32,
    accent: true,
    coupon: {
      id: 'retry1',
      title: 'もう1回',
      description: 'もう一度サイコロを振れます',
      type: 'retry',
    },
  },
  {
    id: 6,
    label: '300円OFF',
    shortLabel: '300円OFF',
    effectLabel: 'クーポン',
    icon: '🎫',
    x: 51,
    y: 30,
    coupon: {
      id: '300off',
      title: '300円OFF',
      description: 'お会計から300円引き',
      type: 'discount',
    },
  },
  {
    id: 7,
    label: '1マス進む',
    shortLabel: '1マス進む',
    effectLabel: 'ラッキー',
    icon: '➡️',
    x: 29,
    y: 34,
    coupon: {
      id: 'forward1',
      title: '1マス進む！',
      description: 'ラッキーマス',
      type: 'special',
    },
  },
  {
    id: 8,
    label: 'ハズレ',
    shortLabel: 'ハズレ',
    effectLabel: 'ざんねん',
    icon: '💭',
    x: 13,
    y: 45,
    coupon: {
      id: 'lose2',
      title: '今回はハズレ',
      description: 'まだまだ先へ進もう',
      type: 'none',
    },
  },
  {
    id: 9,
    label: '限定クーポン',
    shortLabel: '限定',
    effectLabel: 'SPECIAL',
    icon: '⭐',
    x: 30,
    y: 51,
    accent: true,
    coupon: {
      id: 'limited',
      title: '限定クーポン',
      description: '限定特典を獲得',
      type: 'special',
    },
  },
  {
    id: 10,
    label: '100円OFF',
    shortLabel: '100円OFF',
    effectLabel: 'クーポン',
    icon: '🎫',
    x: 50,
    y: 48,
    coupon: {
      id: '100off2',
      title: '100円OFF',
      description: 'お会計から100円引き',
      type: 'discount',
    },
  },
  {
    id: 11,
    label: 'ドリンク無料',
    shortLabel: 'ドリンク無料',
    effectLabel: '1杯無料',
    icon: '🥤',
    x: 70,
    y: 53,
    coupon: {
      id: 'drink2',
      title: 'ドリンク1杯無料',
      description: '対象ドリンクから1杯無料',
      type: 'free',
    },
  },
  {
    id: 12,
    label: '500円OFF',
    shortLabel: '500円OFF',
    effectLabel: 'BIG',
    icon: '💰',
    x: 87,
    y: 63,
    accent: true,
    coupon: {
      id: '500off',
      title: '500円OFF',
      description: 'お会計から500円引き',
      type: 'discount',
    },
  },
  {
    id: 13,
    label: 'ハズレ',
    shortLabel: 'ハズレ',
    effectLabel: 'ざんねん',
    icon: '💭',
    x: 68,
    y: 68,
    coupon: {
      id: 'lose3',
      title: '今回はハズレ',
      description: '次のマスに期待',
      type: 'none',
    },
  },
  {
    id: 14,
    label: 'もう1回',
    shortLabel: 'もう1回',
    effectLabel: 'チャンス',
    icon: '🎲',
    x: 47,
    y: 65,
    coupon: {
      id: 'retry2',
      title: 'もう1回',
      description: 'もう一度サイコロを振れます',
      type: 'retry',
    },
  },
  {
    id: 15,
    label: '300円OFF',
    shortLabel: '300円OFF',
    effectLabel: 'クーポン',
    icon: '🎫',
    x: 26,
    y: 71,
    coupon: {
      id: '300off2',
      title: '300円OFF',
      description: 'お会計から300円引き',
      type: 'discount',
    },
  },
  {
    id: 16,
    label: '大当たり',
    shortLabel: '大当たり',
    effectLabel: 'JACKPOT',
    icon: '🎉',
    x: 13,
    y: 82,
    accent: true,
    coupon: {
      id: 'jackpot',
      title: '大当たり！',
      description: '30分無料クーポン',
      type: 'special',
    },
  },
  {
    id: 17,
    label: 'ドリンク無料',
    shortLabel: 'ドリンク無料',
    effectLabel: '1杯無料',
    icon: '🥤',
    x: 34,
    y: 87,
    coupon: {
      id: 'drink3',
      title: 'ドリンク1杯無料',
      description: '対象ドリンクから1杯無料',
      type: 'free',
    },
  },
  {
    id: 18,
    label: '500円OFF',
    shortLabel: '500円OFF',
    effectLabel: 'BIG',
    icon: '💰',
    x: 58,
    y: 84,
    coupon: {
      id: '500off2',
      title: '500円OFF',
      description: 'お会計から500円引き',
      type: 'discount',
    },
  },
  {
    id: 19,
    label: 'GOAL',
    shortLabel: 'GOAL',
    effectLabel: '',
    icon: '🏆',
    x: 82,
    y: 88,
    accent: true,
    coupon: {
      id: 'goal',
      title: 'GOAL！',
      description: 'ゴール到達。特別クーポン獲得！',
      type: 'special',
    },
  },
]

export const MAX_POSITION = BOARD_SQUARES.length - 1
